name: "Solaris build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v4

    - name: Test on Solaris 11.4
      uses: vmactions/solaris-vm@v1  # see https://github.com/vmactions/solaris-vm
      with:
        release: "11.4-gcc"
        prepare: |
          pkg publisher solaris
          beadm list
          pkg info entire
          pkg list -af entire
          pkg list -af gcc-7
          pkg list -af gcc-11
          pkg install -v --accept developer/gcc-7@7.3.0-11.4.0.0.1.14.0
          pkgutil -y -u
          pkgutil -y -i automake autoconf autoconf_archive libtool pkgconfig libcppunit1_12_1 libcppunit_dev gsed ggrep
        mem: 6144
        run: |
          uname -a
          whoami
          pwd
          cat /etc/release
          PATH=/opt/csw/bin:$PATH
          export PATH
          autoreconf -v --install --force
          ./configure --prefix=/usr
          gmake V=1 -j$(nproc)

